services:
  - type: web
    name: hireme-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: Back-End
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /
